/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.BusquedaVenta;
import GUI.MenuCategoria;
import GUI.MenuProveedor;
import GUI.MenuProducto;
import GUI.RegistroVenta;
import java.awt.Color;

/**
 *
 * @author Luis
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        ocultarMensajes();
    }

    public void ocultarMensajes() {
        panelMensajeCategoria.setVisible(false);
        panelMensajeProductos.setVisible(false);
        panelMensajeProveedores.setVisible(false);
        panelMensajeClientes.setVisible(false);
        panelMensajeRegistroVentas.setVisible(false);
        panelMensajeBusquedaVentas.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBusquedaVenta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelCliente = new javax.swing.JPanel();
        imagenCliente = new javax.swing.JLabel();
        panelProducto = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelProveedor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelCategoria = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        panelMensajeCategoria = new javax.swing.JPanel();
        mensajeCategoria = new javax.swing.JLabel();
        panelMensajeProveedores = new javax.swing.JPanel();
        mensajeProveedores = new javax.swing.JLabel();
        panelMensajeProductos = new javax.swing.JPanel();
        mensajeProductos = new javax.swing.JLabel();
        panelMensajeClientes = new javax.swing.JPanel();
        mensajeClientes = new javax.swing.JLabel();
        panelMensajeRegistroVentas = new javax.swing.JPanel();
        mensajeRegistroVentas = new javax.swing.JLabel();
        panelMensajeBusquedaVentas = new javax.swing.JPanel();
        mensajeBusquedaVentas = new javax.swing.JLabel();
        panelRegistroVenta = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1425, 700));
        setPreferredSize(new java.awt.Dimension(1425, 700));

        panelBusquedaVenta.setBackground(new java.awt.Color(36, 36, 38));
        panelBusquedaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBusquedaVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBusquedaVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBusquedaVentaMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busquedaVenta.png"))); // NOI18N

        javax.swing.GroupLayout panelBusquedaVentaLayout = new javax.swing.GroupLayout(panelBusquedaVenta);
        panelBusquedaVenta.setLayout(panelBusquedaVentaLayout);
        panelBusquedaVentaLayout.setHorizontalGroup(
            panelBusquedaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusquedaVentaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );
        panelBusquedaVentaLayout.setVerticalGroup(
            panelBusquedaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaVentaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        panelCliente.setBackground(new java.awt.Color(36, 36, 38));
        panelCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelClienteMouseExited(evt);
            }
        });

        imagenCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cliente.png"))); // NOI18N

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imagenCliente)
                .addGap(20, 20, 20))
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imagenCliente)
                .addGap(20, 20, 20))
        );

        panelProducto.setBackground(new java.awt.Color(36, 36, 38));
        panelProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelProductoMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto.png"))); // NOI18N

        javax.swing.GroupLayout panelProductoLayout = new javax.swing.GroupLayout(panelProducto);
        panelProducto.setLayout(panelProductoLayout);
        panelProductoLayout.setHorizontalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );
        panelProductoLayout.setVerticalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        panelProveedor.setBackground(new java.awt.Color(36, 36, 38));
        panelProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelProveedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelProveedorMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedor.png"))); // NOI18N

        javax.swing.GroupLayout panelProveedorLayout = new javax.swing.GroupLayout(panelProveedor);
        panelProveedor.setLayout(panelProveedorLayout);
        panelProveedorLayout.setHorizontalGroup(
            panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProveedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(20, 20, 20))
        );
        panelProveedorLayout.setVerticalGroup(
            panelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProveedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(20, 20, 20))
        );

        panelCategoria.setBackground(new java.awt.Color(36, 36, 38));
        panelCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCategoriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCategoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCategoriaMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categoria.png"))); // NOI18N

        javax.swing.GroupLayout panelCategoriaLayout = new javax.swing.GroupLayout(panelCategoria);
        panelCategoria.setLayout(panelCategoriaLayout);
        panelCategoriaLayout.setHorizontalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCategoriaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );
        panelCategoriaLayout.setVerticalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        escritorio.setMinimumSize(new java.awt.Dimension(1400, 400));
        escritorio.setPreferredSize(new java.awt.Dimension(1400, 636));

        panelMensajeCategoria.setBackground(new java.awt.Color(255, 255, 153));

        mensajeCategoria.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mensajeCategoria.setText("Categoria");

        javax.swing.GroupLayout panelMensajeCategoriaLayout = new javax.swing.GroupLayout(panelMensajeCategoria);
        panelMensajeCategoria.setLayout(panelMensajeCategoriaLayout);
        panelMensajeCategoriaLayout.setHorizontalGroup(
            panelMensajeCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMensajeCategoriaLayout.createSequentialGroup()
                .addComponent(mensajeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMensajeCategoriaLayout.setVerticalGroup(
            panelMensajeCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMensajeCategoriaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mensajeCategoria))
        );

        panelMensajeProveedores.setBackground(new java.awt.Color(255, 255, 153));

        mensajeProveedores.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mensajeProveedores.setText("Proveedores");

        javax.swing.GroupLayout panelMensajeProveedoresLayout = new javax.swing.GroupLayout(panelMensajeProveedores);
        panelMensajeProveedores.setLayout(panelMensajeProveedoresLayout);
        panelMensajeProveedoresLayout.setHorizontalGroup(
            panelMensajeProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMensajeProveedoresLayout.createSequentialGroup()
                .addComponent(mensajeProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMensajeProveedoresLayout.setVerticalGroup(
            panelMensajeProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMensajeProveedoresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mensajeProveedores))
        );

        panelMensajeProductos.setBackground(new java.awt.Color(255, 255, 153));

        mensajeProductos.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mensajeProductos.setText("Productos");

        javax.swing.GroupLayout panelMensajeProductosLayout = new javax.swing.GroupLayout(panelMensajeProductos);
        panelMensajeProductos.setLayout(panelMensajeProductosLayout);
        panelMensajeProductosLayout.setHorizontalGroup(
            panelMensajeProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMensajeProductosLayout.createSequentialGroup()
                .addComponent(mensajeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMensajeProductosLayout.setVerticalGroup(
            panelMensajeProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMensajeProductosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mensajeProductos))
        );

        panelMensajeClientes.setBackground(new java.awt.Color(255, 255, 153));

        mensajeClientes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mensajeClientes.setText("Clientes");

        javax.swing.GroupLayout panelMensajeClientesLayout = new javax.swing.GroupLayout(panelMensajeClientes);
        panelMensajeClientes.setLayout(panelMensajeClientesLayout);
        panelMensajeClientesLayout.setHorizontalGroup(
            panelMensajeClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMensajeClientesLayout.createSequentialGroup()
                .addComponent(mensajeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMensajeClientesLayout.setVerticalGroup(
            panelMensajeClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMensajeClientesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mensajeClientes))
        );

        panelMensajeRegistroVentas.setBackground(new java.awt.Color(255, 255, 153));

        mensajeRegistroVentas.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mensajeRegistroVentas.setText("Registro Ventas");

        javax.swing.GroupLayout panelMensajeRegistroVentasLayout = new javax.swing.GroupLayout(panelMensajeRegistroVentas);
        panelMensajeRegistroVentas.setLayout(panelMensajeRegistroVentasLayout);
        panelMensajeRegistroVentasLayout.setHorizontalGroup(
            panelMensajeRegistroVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMensajeRegistroVentasLayout.createSequentialGroup()
                .addComponent(mensajeRegistroVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMensajeRegistroVentasLayout.setVerticalGroup(
            panelMensajeRegistroVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMensajeRegistroVentasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mensajeRegistroVentas))
        );

        panelMensajeBusquedaVentas.setBackground(new java.awt.Color(255, 255, 153));

        mensajeBusquedaVentas.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mensajeBusquedaVentas.setText("Busqueda Ventas");

        javax.swing.GroupLayout panelMensajeBusquedaVentasLayout = new javax.swing.GroupLayout(panelMensajeBusquedaVentas);
        panelMensajeBusquedaVentas.setLayout(panelMensajeBusquedaVentasLayout);
        panelMensajeBusquedaVentasLayout.setHorizontalGroup(
            panelMensajeBusquedaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMensajeBusquedaVentasLayout.createSequentialGroup()
                .addComponent(mensajeBusquedaVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMensajeBusquedaVentasLayout.setVerticalGroup(
            panelMensajeBusquedaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMensajeBusquedaVentasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mensajeBusquedaVentas))
        );

        escritorio.setLayer(panelMensajeCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(panelMensajeProveedores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(panelMensajeProductos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(panelMensajeClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(panelMensajeRegistroVentas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(panelMensajeBusquedaVentas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMensajeCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMensajeProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMensajeClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMensajeRegistroVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMensajeBusquedaVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMensajeProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1177, 1177, 1177))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelMensajeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(panelMensajeProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(panelMensajeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(panelMensajeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(panelMensajeRegistroVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(panelMensajeBusquedaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        panelRegistroVenta.setBackground(new java.awt.Color(36, 36, 38));
        panelRegistroVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRegistroVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRegistroVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRegistroVentaMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registroVenta.png"))); // NOI18N

        javax.swing.GroupLayout panelRegistroVentaLayout = new javax.swing.GroupLayout(panelRegistroVenta);
        panelRegistroVenta.setLayout(panelRegistroVentaLayout);
        panelRegistroVentaLayout.setHorizontalGroup(
            panelRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroVentaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(20, 20, 20))
        );
        panelRegistroVentaLayout.setVerticalGroup(
            panelRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroVentaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(20, 20, 20))
        );

        jPanel1.setBackground(new java.awt.Color(36, 36, 38));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBusquedaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRegistroVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(panelProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(panelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(panelRegistroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(panelBusquedaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelCategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCategoriaMouseEntered
        panelCategoria.setBackground(new Color(65, 65, 68));
        panelMensajeCategoria.setVisible(true);
    }//GEN-LAST:event_panelCategoriaMouseEntered

    private void panelCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCategoriaMouseExited
        panelCategoria.setBackground(new Color(36, 36, 38));
        panelMensajeCategoria.setVisible(false);
    }//GEN-LAST:event_panelCategoriaMouseExited

    private void panelProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProveedorMouseEntered
        panelProveedor.setBackground(new Color(65, 65, 68));
        panelMensajeProveedores.setVisible(true);
    }//GEN-LAST:event_panelProveedorMouseEntered

    private void panelProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProveedorMouseExited
        panelProveedor.setBackground(new Color(36, 36, 38));
        panelMensajeProveedores.setVisible(false);
    }//GEN-LAST:event_panelProveedorMouseExited

    private void panelProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProductoMouseEntered
        panelProducto.setBackground(new Color(65, 65, 68));
        panelMensajeProductos.setVisible(true);
    }//GEN-LAST:event_panelProductoMouseEntered

    private void panelProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProductoMouseExited
        panelProducto.setBackground(new Color(36, 36, 38));
        panelMensajeProductos.setVisible(false);
    }//GEN-LAST:event_panelProductoMouseExited

    private void panelClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelClienteMouseEntered
        panelCliente.setBackground(new Color(65, 65, 68));
        panelMensajeClientes.setVisible(true);
    }//GEN-LAST:event_panelClienteMouseEntered

    private void panelClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelClienteMouseExited
        panelCliente.setBackground(new Color(36, 36, 38));
        panelMensajeClientes.setVisible(false);
    }//GEN-LAST:event_panelClienteMouseExited

    private void panelBusquedaVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBusquedaVentaMouseEntered
        panelBusquedaVenta.setBackground(new Color(65, 65, 68));
        panelMensajeBusquedaVentas.setVisible(true);
    }//GEN-LAST:event_panelBusquedaVentaMouseEntered

    private void panelBusquedaVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBusquedaVentaMouseExited
        panelBusquedaVenta.setBackground(new Color(36, 36, 38));
        panelMensajeBusquedaVentas.setVisible(false);
    }//GEN-LAST:event_panelBusquedaVentaMouseExited

    private void panelRegistroVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegistroVentaMouseEntered
        panelRegistroVenta.setBackground(new Color(65, 65, 68));
        panelMensajeRegistroVentas.setVisible(true);
    }//GEN-LAST:event_panelRegistroVentaMouseEntered

    private void panelRegistroVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegistroVentaMouseExited
        panelRegistroVenta.setBackground(new Color(36, 36, 38));
        panelMensajeRegistroVentas.setVisible(false);
    }//GEN-LAST:event_panelRegistroVentaMouseExited

  
    private void panelCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCategoriaMouseClicked
        MenuCategoria ventanaCategoria = new MenuCategoria();
        escritorio.add(ventanaCategoria);
        ventanaCategoria.show();
    }//GEN-LAST:event_panelCategoriaMouseClicked

    private void panelProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProveedorMouseClicked
        MenuProveedor ventanaProveedor = new MenuProveedor();
        escritorio.add(ventanaProveedor);
        ventanaProveedor.show();
    }//GEN-LAST:event_panelProveedorMouseClicked

    private void panelProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProductoMouseClicked
        MenuProducto ventanaProducto = new MenuProducto();
        escritorio.add(ventanaProducto);
        ventanaProducto.show();
    }//GEN-LAST:event_panelProductoMouseClicked

    private void panelRegistroVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegistroVentaMouseClicked
        RegistroVenta ventanaRegistroVenta = new RegistroVenta();
        escritorio.add(ventanaRegistroVenta);
        ventanaRegistroVenta.show();
    }//GEN-LAST:event_panelRegistroVentaMouseClicked

    private void panelBusquedaVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBusquedaVentaMouseClicked
        BusquedaVenta ventanaBusquedaVenta = new BusquedaVenta();
        escritorio.add(ventanaBusquedaVenta);
        ventanaBusquedaVenta.show();
    }//GEN-LAST:event_panelBusquedaVentaMouseClicked

    private void panelClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelClienteMouseClicked
        MenuCliente menuCliente = new MenuCliente();
        escritorio.add(menuCliente);
        menuCliente.show();
    }//GEN-LAST:event_panelClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel imagenCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensajeBusquedaVentas;
    private javax.swing.JLabel mensajeCategoria;
    private javax.swing.JLabel mensajeClientes;
    private javax.swing.JLabel mensajeProductos;
    private javax.swing.JLabel mensajeProveedores;
    private javax.swing.JLabel mensajeRegistroVentas;
    private javax.swing.JPanel panelBusquedaVenta;
    private javax.swing.JPanel panelCategoria;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelMensajeBusquedaVentas;
    private javax.swing.JPanel panelMensajeCategoria;
    private javax.swing.JPanel panelMensajeClientes;
    private javax.swing.JPanel panelMensajeProductos;
    private javax.swing.JPanel panelMensajeProveedores;
    private javax.swing.JPanel panelMensajeRegistroVentas;
    private javax.swing.JPanel panelProducto;
    private javax.swing.JPanel panelProveedor;
    private javax.swing.JPanel panelRegistroVenta;
    // End of variables declaration//GEN-END:variables
}
