CREATE SCHEMA `punto_Venta`;

USE `punto_Venta`;

CREATE TABLE `Categoria`(`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `nombre` VARCHAR(50) NOT NULL, `descripcion` VARCHAR(50) NOT NULL);

CREATE TABLE `Proveedor`(`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `rfc` VARCHAR(13) NOT NULL, `nombre` VARCHAR(50) NOT NULL, `direccion` VARCHAR(50) NOT NULL, `telefono` VARCHAR(50) NOT NULL, `paginaWeb` VARCHAR(50) NOT NULL);

CREATE TABLE `Producto`(`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `nombre` VARCHAR(50) NOT NULL, `precioActual` DECIMAL(10,2) NOT NULL, `stock` INT NOT NULL,
`idProvedor` INT NOT NULL, `idCategoria` INT NOT NULL);

SHOW COLUMNS FROM `Producto`;

ALTER TABLE `Producto` ADD CONSTRAINT fk_CatPro FOREIGN KEY (`idCategoria`) REFERENCES `Categoria`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Producto` ADD CONSTRAINT fk_ProvPro FOREIGN KEY (`idProvedor`) REFERENCES `Proveedor`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE `Cliente`(`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `rfc` VARCHAR(13) NOT NULL, `nombre` VARCHAR(50) NOT NULL, `direccion` VARCHAR(50) NOT NULL, `telefono1` VARCHAR(50) NOT NULL, `telefono2` VARCHAR(50) NOT NULL);

CREATE TABLE `Venta`(`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `fecha` DATE NOT NULL, `descuento` DECIMAL(10,2) NOT NULL, 
`montoFinal` FLOAT NOT NULL, `idCliente` INT NOT NULL);

ALTER TABLE `Venta` ADD CONSTRAINT fk_CusSale FOREIGN KEY (`idCliente`) REFERENCES `Cliente`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE `relProductoVentas`(`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `idProducto` INT NOT NULL, `idVenta` INT NOT NULL, `precio` FLOAT NOT NULL, `cantidad` int(11) NOT NULL,`montototal` FLOAT NOT NULL);

ALTER TABLE `relProductoVentas` ADD CONSTRAINT fk_ProSale FOREIGN KEY (`idProducto`) REFERENCES `Producto`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `relProductoVentas` ADD CONSTRAINT fk_SaleSale FOREIGN KEY (`idVenta`) REFERENCES `Venta`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;


